apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - atlas.example.com
      secretName: atlas-tls
  rules:
    - host: atlas.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: atlas-api
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: atlas-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-web
                port:
                  number: 80
